# Generated by Django 5.1 on 2024-08-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_message_user_room_host_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
